"""Committed version stamp — GENERATED by tools/package_clients.py; do not hand-edit.

ADR-0005 Ruling 1: the clean-room export ships only git-tracked files, so the
zero-install VM (staged source, no package metadata) can only report a real
version if this stamp is COMMITTED. tools/release.py rewrites it (via
tools/package_clients.py) in the same act as the pyproject.toml bump, so the
tagged release commit always carries the exact released version. On the
pip-installed host, importlib.metadata stays primary; brain/__init__.py reads
this file only as the fallback before 0.0.0+unknown.
"""

__version__ = "0.12.0"
