"""DLV-10 — the owner-facing index published inside the deliverables shelf.

The shelf is a folder of files with no context: a copy of an archived original
carries the original's filename and nothing else — not what it is, not which
project it belongs to, not how sensitive it is, and not why there is a
``_previous/`` folder beside it. This renders that context as one ``README.md``
at the shelf root, from the HOST-PRIVATE ledger and nothing else, so a hand-
dropped file can never appear in it as though the fold put it there.

It leads with the highest classification present, because the folder is
consumed as a whole: someone about to attach three files from it needs the
ceiling before the details. The rows are newest-first for the same reason —
the thing an owner came for is almost always the most recent.

Version ambiguity is FLAGGED here and resolved nowhere: ``AGENTS.md`` makes
supersession beyond ``…-vN`` a PROPOSAL that is never applied, so two
hand-saved versions of one deck are both latest and both legitimately reach
the shelf. Naming the pair beside the files is the honest report; picking a
winner would be a second, competing supersession mechanism.
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from . import classification as CLS
from . import deliverables_ledger as L
from . import lock as _lock

_HEADER = ("| Updated | Title | Project | Tier | File | Note |\n"
           "|---|---|---|---|---|---|\n")


def _cell(value: object) -> str:
    """One markdown table cell. A ``|`` or a newline in a note title would
    otherwise shear the table into nonsense."""
    text = " ".join(str(value or "").split())
    return text.replace("|", "\\|") or "—"


def _human_bytes(total: int) -> str:
    step = float(total)
    for unit in ("B", "KB", "MB", "GB"):
        if step < 1024 or unit == "GB":
            return f"{step:.0f} {unit}" if unit == "B" else f"{step:.1f} {unit}"
        step /= 1024
    return f"{total} B"


def _highest_tier(rows: dict[str, dict[str, Any]]) -> str:
    """The most restrictive tier on the shelf. Default-denied through
    ``CLS.rank``, so an unlabelled row raises the header rather than
    lowering it."""
    if not rows:
        return CLS.TIERS[0]
    return CLS.TIERS[max(CLS.rank(str(r.get("tier") or "")) for r in rows.values())]


def render(rows: dict[str, dict[str, Any]], ambiguous: list[dict[str, Any]],
           previous: dict[str, int]) -> str:
    """The whole page. Pure — the caller does the writing."""
    ordered = sorted(rows.items(),
                     key=lambda kv: (str(kv[1].get("updated") or ""), kv[0]),
                     reverse=True)
    lines = [
        "# Deliverables shelf",
        "",
        f"**Highest classification here: {_highest_tier(rows)}.** The payload "
        "is the archived original, not the note about it — treat every file "
        "in this folder at that tier.",
        "",
        f"{len(rows)} file(s), newest first. Generated by `brain maintain`; "
        "edits to this file are overwritten on the next run, and a file you "
        "drop in here yourself is reported but never touched or listed below.",
        "",
        f"`_previous/` holds {previous.get('files', 0)} retired file(s) "
        f"({_human_bytes(int(previous.get('bytes', 0)))}), grouped by the run "
        "that moved them: nothing on this shelf is ever deleted, only moved "
        "aside when a newer version arrives or the deliverable is retired.",
        "",
    ]
    if ambiguous:
        lines += [
            "## Two versions, both current",
            "",
            "These names each belong to more than one note, so both copies "
            "are on the shelf under a note-id suffix. Retiring one is a "
            "`brain supersede` decision, not something this folder makes:",
            "",
        ]
        lines += [f"- `{item['name']}` — {', '.join(item['note_ids'])}"
                  for item in ambiguous]
        lines.append("")
    lines += ["## What is here", "", _HEADER.rstrip("\n")]
    lines += [
        f"| {_cell(row.get('updated'))} | {_cell(row.get('title'))} "
        f"| {_cell(row.get('project'))} | {_cell(row.get('tier'))} "
        f"| `{rel}` | `{_cell(row.get('note_id'))}` |"
        for rel, row in ordered
    ]
    return "\n".join(lines) + "\n"


def publish(shelf: Path, rows: dict[str, dict[str, Any]],
            ambiguous: list[dict[str, Any]], previous: dict[str, int],
            bad_perms: list[str]) -> None:
    """Write the README owner-only, atomically. Same posture as the advisory
    manifest beside it: written for a human, never read back for authority."""
    path = shelf / L.README_FILENAME
    tmp = _lock._atomic_temp_path(path)
    try:
        tmp.write_text(render(rows, ambiguous, previous), encoding="utf-8")
        os.chmod(tmp, L.FILE_MODE)
        os.replace(tmp, path)
    finally:
        tmp.unlink(missing_ok=True)
    if not L.secure(path, L.FILE_MODE):
        bad_perms.append(str(path))
