"""Doctor surface resolution stages (s18 extraction).

The path, marketplace, registry and repo-root resolution moved verbatim out
of ``doctor.run_doctor``; the report orchestration stays in
:mod:`brain.doctor` with an unchanged signature. This module imports
:mod:`brain.doctor` only lazily (inside function bodies, below) — never at
module load time — so :mod:`brain.doctor` can import THIS module back at its
own load time without a cycle.
"""
from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path
from typing import Any, Optional


def marketplace_install_location(claude_home: Path, name: str = "brainiac") -> Optional[Path]:
    """The one already-persisted authoritative pointer to the marketplace's
    on-disk checkout (RC1/RC3/RC4). ``~/.claude/plugins/known_marketplaces.json``
    is a FLAT dict keyed by marketplace name (verified on-machine: no
    "marketplaces" wrapper — same read as ``check_stale_name_plugins``), each
    value carrying an ``installLocation``. A directory-source marketplace (this
    machine: ``installLocation`` == the engine checkout) records the REAL path
    there, so reading it fixes three bugs at once: the hardcoded
    ``marketplaces/<name>`` guess that read a directory-source install as "not
    installed" (RC3), the ``__file__``-inference that mislocated ``repo_root``
    on a wheel install (RC1/RC4), and the ``~/brainiac`` engine-src fallback
    (RC1). Returns ``None`` when the file, the key, or the dir is absent —
    every caller keeps its own fallback."""
    known = _read_json(claude_home / "plugins" / "known_marketplaces.json")
    if not isinstance(known, dict):
        return None
    entry = known.get(name)
    if not isinstance(entry, dict):
        return None
    loc = entry.get("installLocation")
    if not loc:
        return None
    p = Path(str(loc)).expanduser()
    return p if p.is_dir() else None


def resolve_marketplace_dir(claude_home: Path, marketplace_dir: Optional[Path],
                            marketplace_name: str) -> tuple[Path, Optional[Path]]:
    """Return (marketplace_dir, resolved_location) for the doctor surfaces.

    RC1/RC3/RC4: the marketplace's real on-disk location comes from
    known_marketplaces.json → installLocation (a directory-source
    marketplace is NOT under marketplaces/<name>). Resolve it once and reuse
    for both the marketplace-cache row and the installed-plugin rows; keep
    the hardcoded path as the last fallback.
    """
    resolved_marketplace = marketplace_install_location(claude_home, marketplace_name)
    marketplace_dir = (
        marketplace_dir
        or resolved_marketplace
        or (claude_home / "plugins" / "marketplaces" / marketplace_name)
    )
    return marketplace_dir, resolved_marketplace


def resolve_registry_entries(repo_root: Path) -> tuple[list[dict[str, Any]], bool]:
    """Load the workspace registry entries, degrading to (entries=[], unavailable)."""
    try:
        import workspace_registry as _wr                          # noqa: PLC0415

        return _wr.list_entries(), False
    except Exception:
        # HARDEN: `tools/workspace_registry.py` is a host-only companion
        # script — never part of the staged zero-install engine
        # (cowork_workspace_install.sh copies only src/brain). A staged
        # VM copy invoking `brain doctor` with role=host (e.g. the shim
        # doesn't set $BRAIN_ROLE) must degrade to "can't check this
        # surface", never crash with a raw ModuleNotFoundError.
        return [], True


def resolve_repo_root(repo_root: Path,
                      resolved_marketplace: Optional[Path]) -> Path:
    """Return the checkout the repo-oriented rows should score against.

    Repo-oriented surfaces (SSOT/stamp/dist/plugin-manifests) only mean
    anything on a DEV CHECKOUT. From an installed engine (dist venv, uv
    tool, pipx) repo_root resolves inside site-packages, so those rows came
    back UNKNOWN — a gating status — and every health report generated by a
    pinned engine read falsely DEGRADED (field finding 2026-07-20, caught in
    the v0.19.3 pre-restage verification). Without a checkout the honest
    answer is NOT_DETECTABLE, and drift comparisons fall back to the running
    engine's own version.
    RC4: when __file__-inference lands somewhere without a pyproject (a wheel
    install resolves repo_root inside site-packages), retry via the
    marketplace installLocation — the real checkout on a directory-source
    install. This turns a falsely "installed engine, no checkout" host back
    into a full dev-checkout doctor run (staged-workspace rows, SSOT drift).
    """
    if not (repo_root / "pyproject.toml").is_file():
        retry = resolved_marketplace
        if retry and (retry / "pyproject.toml").is_file() and (retry / "src" / "brain").is_dir():
            return retry
    return repo_root


def sys_path_with_tools(repo_root: Path) -> None:
    """Put the checkout's tools/ first on sys.path (workspace_registry loader)."""
    sys.path.insert(0, str(repo_root / "tools"))


def resolved_brain_bin() -> Optional[Path]:
    """The `brain` executable this machine resolves, if any."""
    found = shutil.which("brain")
    return Path(found) if found else None


def brainiac_home_default() -> Path:
    """$BRAINIAC_HOME or ~/.brainiac."""
    return Path(os.environ.get("BRAINIAC_HOME", Path.home() / ".brainiac"))


def build_context_and_checks(
    *, repo_root, brainiac_home, claude_home, app_support_dir,
    registry_entries, marketplace_dir, marketplace_name, registry_fetch,
    vault, resolved_brain, is_dev_checkout, schema_version, engine_version,
    registry_unavailable, vm_python) -> tuple[Any, Any]:
    """Assemble the (context, checks) pair the doctor rows run against.

    The check callables are resolved from :mod:`brain.doctor` LAZILY, inside
    this function, because that module imports this one — at call time it is
    fully loaded, and no test monkeypatches these names.
    """
    from . import config as _config
    from . import doctor as _doctor
    from .doctor_checks import DoctorCheckContext, DoctorChecks

    context = DoctorCheckContext(
        repo_root=repo_root,
        brainiac_home=brainiac_home,
        claude_home=claude_home,
        app_support_dir=app_support_dir,
        registry_entries=registry_entries,
        marketplace_dir=marketplace_dir,
        marketplace_name=marketplace_name,
        registry_fetch=registry_fetch,
        vault=vault,
        resolved_brain=resolved_brain,
        is_dev_checkout=is_dev_checkout,
        schema_version=schema_version,
        engine_version=engine_version,
        registry_unavailable=registry_unavailable,
        vm_python=vm_python,
    )
    checks = DoctorChecks(
        row=_doctor._row,
        ssot_version=_doctor._ssot_version,
        committed_stamp=_doctor.check_committed_stamp,
        host_venv=_doctor.check_host_venv,
        embedder_liveness=_doctor.check_embedder_liveness,
        dist_compat=_doctor.check_dist_compat,
        plugin_manifests=_doctor.check_plugin_manifests,
        installed_cli_plugins=_doctor.check_installed_cli_plugins,
        stale_name_plugins=_doctor.check_stale_name_plugins,
        staged_workspaces=_doctor.check_staged_workspaces,
        vendor_abi=_doctor.check_vendor_abi,
        staged_skill_bundles=_doctor.check_staged_skill_bundles,
        workspace_schema=_doctor.check_workspace_schema,
        maintain_heartbeat=_doctor.check_vm_maintain_heartbeat,
        marketplace_cache=_doctor.check_marketplace_cache,
        vault_root=_config.vault_root,
        query_capture=_doctor.check_query_capture,
        audit_content_drift=_doctor.check_audit_content_drift,
        corpus_invariants=_doctor.check_corpus_invariants,
        pypi_registry_drift=_doctor.check_pypi_registry_drift,
        mcpb_desktop_collision=_doctor.check_mcpb_desktop_collision,
        mcp_vault_paths=_doctor.check_mcp_vault_paths,
        cos_deployed_skill=_doctor.check_cos_deployed_skill,
        desktop_plugin_store=_doctor.check_desktop_plugin_store,
        cowork_vault_dir=_doctor._cowork_vault_dir,
        quarantine=_doctor.check_quarantine,
        ingest_capability=_doctor.check_ingest_capability,
        unreadable_registry_row=_doctor._unreadable_registry_row,
    )
    return context, checks


# Parent-namespace bind, deferred past this module's own defs. Safe: this
# module is only ever first imported (by ``doctor.run_doctor``'s lazy
# ``import doctor_context``, or by the facade re-export below) after
# :mod:`brain.doctor` has already defined ``_read_json`` at its own top.
from .doctor import _read_json as _read_json  # noqa: E402
