"""HYG-02 — framework-sync drift audit (ADR-0003 Ruling 5).

Covers the SKILL_VERSION false-positive trap directly: a freshly-synced tree
(mirror carries the generated stamp line canonical never has) must report
ZERO drift. A genuine content divergence must still be caught.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "tools"))
import framework_sync as fsync  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[1]


def _write_skill(root: Path, name: str, body: str) -> Path:
    d = root / name
    d.mkdir(parents=True, exist_ok=True)
    (d / "SKILL.md").write_text(body, encoding="utf-8")
    return d


def _fake_tree(tmp_path: Path):
    claude = tmp_path / "claude-skills"
    agents = tmp_path / "agents-skills"
    plugins = tmp_path / "plugins"

    kernel_body = "---\nname: fake-kernel\ndescription: x\n---\nbody\n"
    _write_skill(claude, "fake-kernel", kernel_body)
    _write_skill(agents, "fake-kernel", kernel_body)  # byte-identical mirror
    _write_skill(plugins / "profile-a-kernel" / "skills", "fake-kernel", kernel_body)

    brainiac_canonical = "---\nname: fake-manager\ndescription: y\n---\nbody\n"
    stamp = "\n<!-- SKILL_VERSION: 9.9.9 (generated by tools/package_clients.py — do not hand-edit) -->\n"
    _write_skill(claude, "fake-manager", brainiac_canonical)
    _write_skill(agents, "fake-manager", brainiac_canonical + stamp)
    _write_skill(plugins / "brainiac-manager" / "skills", "fake-manager", brainiac_canonical + stamp)

    return claude, agents, plugins


def test_freshly_synced_tree_reports_zero_drift(tmp_path):
    """The clean case — catches the SKILL_VERSION false-positive trap: the
    brainiac-manager mirror has an extra generated stamp line the canonical
    copy never carries, and that must NOT be reported as drift."""
    claude, agents, plugins = _fake_tree(tmp_path)
    drift = fsync.check_skill_drift(
        claude_skills_dir=claude, agents_skills_dir=agents, plugins_dir=plugins,
        kernel_skills=["fake-kernel"], extras_skills=[], brainiac_skills=["fake-manager"],
    )
    assert drift == []


def test_injected_drift_is_detected(tmp_path):
    claude, agents, plugins = _fake_tree(tmp_path)
    # Injected drift: hand-edit the mirror's real content (not the stamp).
    (agents / "fake-kernel" / "SKILL.md").write_text("---\nname: fake-kernel\ndescription: x\n---\nDRIFTED\n")

    drift = fsync.check_skill_drift(
        claude_skills_dir=claude, agents_skills_dir=agents, plugins_dir=plugins,
        kernel_skills=["fake-kernel"], extras_skills=[], brainiac_skills=["fake-manager"],
    )
    assert len(drift) == 1
    assert drift[0]["skill"] == "fake-kernel"
    assert drift[0]["mirror"] == ".agents/skills"
    assert drift[0]["reason"] == "content differs"


def test_claude_md_import_check(tmp_path):
    ok_path = tmp_path / "CLAUDE.md"
    ok_path.write_text("# CLAUDE.md\n\n@AGENTS.md\n\nmore text\n")
    assert fsync.check_claude_md_import(ok_path)["ok"] is True

    broken_path = tmp_path / "CLAUDE-broken.md"
    broken_path.write_text("# CLAUDE.md\n\nno import here\n")
    assert fsync.check_claude_md_import(broken_path)["ok"] is False

    missing_path = tmp_path / "does-not-exist.md"
    assert fsync.check_claude_md_import(missing_path)["ok"] is False


def test_real_repo_tree_is_currently_clean():
    """Integration sanity check against the ACTUAL committed repo — this is
    the check that would have caught a real SKILL_VERSION false positive:
    the real brainiac-* mirrors DO carry the generated stamp."""
    report = fsync.audit()
    assert report["skill_drift"] == []
    assert report["claude_md_import"]["ok"] is True
    assert report["clean"] is True


def test_framework_sync_finding_shapes_action_required_and_none_when_clean():
    sys.path.insert(0, str(REPO_ROOT / "src"))
    from brain import maintenance as maint

    assert maint.framework_sync_finding({"clean": True, "skill_drift": [], "claude_md_import": {"ok": True}}) is None

    dirty = {
        "clean": False,
        "skill_drift": [{"skill": "kb-curator", "mirror": ".agents/skills", "path": "SKILL.md", "reason": "content differs"}],
        "claude_md_import": {"ok": True, "reason": None},
    }
    finding = maint.framework_sync_finding(dirty)
    assert finding is not None
    assert "kb-curator" in finding["inspect"]
    assert "package_clients.py" in finding["proposed_action"]
