"""COS priority-map operations."""
from __future__ import annotations

from ._shared import *  # noqa: F401,F403
from ._facade import public
from ._io import _write_atomic
from ._layout import _ts, _utcnow, priority_map_path

def load_priority_overrides(vault) -> dict[str, str]:
    """Owner overrides from the validated overlay ``cos/`` category: body list
    lines of the form ``- <note-id>: high|normal|low|exclude``."""
    from .. import overlay as ov

    overrides: dict[str, str] = {}
    cos_cat = ov.overlay_dir(vault) / "cos"
    if not cos_cat.is_dir():
        return overrides
    for f in sorted(cos_cat.glob("*.md")):
        try:
            _meta, body = frontmatter.parse_text(f.read_text(encoding="utf-8"))
        except OSError:
            continue
        for line in body.splitlines():
            m = _OVERRIDE_LINE_RE.match(line)
            if m:
                overrides[m.group("id").lower()] = m.group("prio").lower()
    return overrides

def generate_priority_map(core, *, max_tier: str | None = None,
                          now: _dt.datetime | None = None) -> dict[str, Any]:
    """Generate ``shared/priority-map.md`` from ``type: person``/``company``
    notes via a HOST-produced filtered projection. Default tier policy: the
    FULL vault (host egress default, owner ruling 2026-07-10) — deliberately
    NOT capped to Internal; pass ``max_tier`` to narrow. Owner overrides come
    from the overlay ``cos/`` category. The output lists ids/titles/metadata
    only — never note bodies."""
    from .. import classification as cls
    from .. import egress

    now = now or _utcnow()
    tier = max_tier or cls.TIERS[-1]
    people = core.bases_query({"type": "person"}, k=1000)
    companies = core.bases_query({"type": "company"}, k=1000)
    gated_people, prep = egress.apply_gate(people, tier)
    gated_companies, crep = egress.apply_gate(companies, tier)
    overrides = load_priority_overrides(core.vault)

    def _bucketed(items: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
        buckets: dict[str, list[dict[str, Any]]] = {"high": [], "normal": [], "low": []}
        for it in sorted(items, key=lambda x: str(x.get("updated") or ""), reverse=True):
            prio = overrides.get(str(it.get("id", "")).lower(), "normal")
            if prio == "exclude":
                continue
            buckets[prio].append(it)
        return buckets

    sections = {"People": _bucketed(gated_people),
                "Companies": _bucketed(gated_companies)}
    lines = [
        "<!-- GENERATED by `brain cos-priority-map` — do not hand-edit. -->",
        f"<!-- generated: {_ts(now)} max_tier: {tier} "
        f"overrides: {len(overrides)} -->",
        "# COS priority map", "",
    ]
    for heading, buckets in sections.items():
        lines.append(f"## {heading}")
        for prio in ("high", "normal", "low"):
            for it in buckets[prio]:
                lines.append(
                    f"- [[{it.get('id')}]] — {it.get('title') or it.get('id')} "
                    f"(priority: {prio}, {it.get('classification') or 'UNLABELLED'}, "
                    f"updated {it.get('updated') or '?'})")
        lines.append("")
    out_path = priority_map_path(core.vault)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    public("_write_atomic")(out_path, ("\n".join(lines).rstrip() + "\n").encode("utf-8"),
                  mode=MODE_VM_READABLE)
    return {"path": str(out_path), "max_tier": tier,
            "people": len(gated_people), "companies": len(gated_companies),
            "withheld": prep["withheld"] + crep["withheld"],
            "overrides": overrides}

__all__ = ['load_priority_overrides', 'generate_priority_map']
