"""The version-propagation lane of `package_clients.py` — SSOT version read, stamp writes, lockstep validation (batch-2 drain).

Moved verbatim out of `tools/package_clients.py`; the parent re-imports every
name, so `pc.read_source_version()` / `pc.validate_monotonic_version(...)` keep
their original module path (`tests/test_release.py` imports them there).
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from package_shared import (  # noqa: E402
    DIST_DIR, PLUGINS_DIR, PYPROJECT_PATH, REPO_ROOT, ValidationError,
    validate_json_file)

# ---------------------------------------------------------------------------
# SKILL_VERSION / dist/COMPAT — generated version marker (VERIFY-ROUND-1)
#
# /brainiac-update (s03) compares this marker against ~/brainiac's code
# version to detect skill<->code skew. It MUST be produced here, from the
# same pyproject.toml version the code ships, never hand-maintained in any
# SKILL.md — otherwise the version contract the update skill relies on is
# unenforceable.
# ---------------------------------------------------------------------------


def read_source_version() -> str:
    text = PYPROJECT_PATH.read_text(encoding="utf-8")
    m = re.search(r'(?m)^version\s*=\s*"([^"]+)"', text)
    if not m:
        raise ValidationError(f"{PYPROJECT_PATH}: no top-level version = \"...\" found")
    return m.group(1)


def write_compat_marker(version: str) -> Path:
    DIST_DIR.mkdir(parents=True, exist_ok=True)
    compat_path = DIST_DIR / "COMPAT"
    compat_path.write_text(version + "\n", encoding="utf-8")
    return compat_path


# ---------------------------------------------------------------------------
# Committed version stamp (ADR-0005 Ruling 1) — src/brain/_version.py is the
# from-source fallback the zero-install VM and the clean-room export report.
# It MUST be git-committed (the export ships only git-tracked files), and it
# is rewritten here — release.py runs this packager in the same act as the
# pyproject bump — so staleness is structurally impossible.
# ---------------------------------------------------------------------------

VERSION_STAMP_PATH = REPO_ROOT / "src" / "brain" / "_version.py"
VERSION_STAMP_RE = re.compile(r'(?m)^__version__ = "([^"]+)"$')

VERSION_STAMP_TEMPLATE = '''"""Committed version stamp — GENERATED by tools/package_clients.py; do not hand-edit.

ADR-0005 Ruling 1: the clean-room export ships only git-tracked files, so the
zero-install VM (staged source, no package metadata) can only report a real
version if this stamp is COMMITTED. tools/release.py rewrites it (via
tools/package_clients.py) in the same act as the pyproject.toml bump, so the
tagged release commit always carries the exact released version. On the
pip-installed host, importlib.metadata stays primary; brain/__init__.py reads
this file only as the fallback before 0.0.0+unknown.
"""

__version__ = "{version}"
'''


def write_version_stamp(version: str) -> Path:
    content = VERSION_STAMP_TEMPLATE.format(version=version)
    if not VERSION_STAMP_PATH.exists() or VERSION_STAMP_PATH.read_text(encoding="utf-8") != content:
        VERSION_STAMP_PATH.write_text(content, encoding="utf-8")
    return VERSION_STAMP_PATH


def validate_version_stamp(version: str) -> None:
    """Hard error if src/brain/_version.py is missing or != the pyproject SSOT
    (ADR-0005 Ruling 1 — a stale committed stamp is worse than 0.0.0+unknown)."""
    if not VERSION_STAMP_PATH.exists():
        raise ValidationError(f"missing {VERSION_STAMP_PATH} (ADR-0005 Ruling 1 committed version stamp)")
    m = VERSION_STAMP_RE.search(VERSION_STAMP_PATH.read_text(encoding="utf-8"))
    if not m:
        raise ValidationError(f"{VERSION_STAMP_PATH}: no __version__ = \"...\" line found")
    if m.group(1) != version:
        raise ValidationError(
            f"{VERSION_STAMP_PATH}: stamp {m.group(1)!r} != pyproject.toml SSOT version {version!r} "
            "(ADR-0005 Ruling 1 — rerun tools/package_clients.py and commit the stamp)"
        )


# ---------------------------------------------------------------------------
# Plugin version propagation (ADR-0004 Ruling 1/5, s06) — the three
# plugin.json files carry no independent version line; the SSOT is written
# into all of them at package time, and --validate-only hard-fails any skew.
# ---------------------------------------------------------------------------

PLUGIN_NAMES = ["brainiac-manager", "brainiac-kernel", "brainiac-extras"]


def write_plugin_versions(version: str) -> list[Path]:
    written: list[Path] = []
    for pname in PLUGIN_NAMES:
        plugin_json_path = PLUGINS_DIR / pname / ".claude-plugin" / "plugin.json"
        data = validate_json_file(plugin_json_path)
        if data.get("version") != version:
            data["version"] = version
            plugin_json_path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        written.append(plugin_json_path)
    return written


# The npm bootstrap installer (packaging/npm/brainiac-install) is a FOURTH
# published artifact, on its own registry. It was bumped by hand in every
# release commit until 0.19.10, when a release cut through tools/release.py
# left it a version behind and every lockstep check still reported OK — the
# validator simply did not know it existed. It is on the SSOT now.
NPM_PACKAGE_JSON = REPO_ROOT / "packaging" / "npm" / "brainiac-install" / "package.json"


def write_npm_version(version: str) -> Path:
    data = validate_json_file(NPM_PACKAGE_JSON)
    if data.get("version") != version:
        data["version"] = version
        NPM_PACKAGE_JSON.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return NPM_PACKAGE_JSON


def validate_npm_version_lockstep(version: str) -> None:
    """Hard error if the npm bootstrap's version != the pyproject SSOT version.

    Same rule as the plugin manifests (ADR-0004 Ruling 5): one version line
    across every published artifact, skew is an error, not a warning."""
    data = validate_json_file(NPM_PACKAGE_JSON)
    nversion = data.get("version")
    if nversion != version:
        raise ValidationError(
            f"{NPM_PACKAGE_JSON}: version {nversion!r} != pyproject.toml SSOT version {version!r} "
            "(ADR-0004 Ruling 5 — single version line, skew is a hard error)"
        )


def validate_monotonic_version(version: str) -> None:
    """ADR-0005 Ruling 5 (GV-01): hard-fail if the SSOT version on disk is not
    strictly greater than the release baseline (highest semver-shaped local
    tag, or itself if no such tag exists — a same-as-baseline version is fine
    here, since --validate-only runs on a checkout that may already be AT the
    just-cut version; only a real regression below the baseline must fail).
    Reuses tools/release.py's guard so the rule lives in exactly one place."""
    sys.path.insert(0, str(REPO_ROOT / "tools"))
    import release as _release  # local import: avoid a hard import-time coupling for callers that only need packaging

    baseline = _release.monotonic_baseline(version)
    if _release._version_key(version) < _release._version_key(baseline):
        raise ValidationError(
            f"pyproject.toml SSOT version {version!r} is lower than the release baseline "
            f"{baseline!r} (highest semver-shaped local tag) — ADR-0005 Ruling 5 monotonic guard"
        )


def validate_plugin_version_lockstep(version: str) -> None:
    """Hard error on ANY plugin.json version != the pyproject SSOT version
    (ADR-0004 Ruling 5: single version line, skew-is-error)."""
    for pname in PLUGIN_NAMES:
        plugin_json_path = PLUGINS_DIR / pname / ".claude-plugin" / "plugin.json"
        data = validate_json_file(plugin_json_path)
        pversion = data.get("version")
        if pversion != version:
            raise ValidationError(
                f"{plugin_json_path}: version {pversion!r} != pyproject.toml SSOT version {version!r} "
                "(ADR-0004 Ruling 5 — single version line, skew is a hard error)"
            )


def stamp_skill_version(skill_md_path: Path, version: str) -> None:
    """Append a generated SKILL_VERSION marker line to a DISTRIBUTED copy of a
    SKILL.md (never the canonical .claude/skills/ source)."""
    text = skill_md_path.read_text(encoding="utf-8")
    marker = f"<!-- SKILL_VERSION: {version} (generated by tools/package_clients.py — do not hand-edit) -->\n"
    # Match only a real marker on its own line — prose may mention
    # "<!-- SKILL_VERSION: ... -->" mid-line (e.g. brainiac-update docs).
    marker_re = re.compile(r"^<!-- SKILL_VERSION:.*?-->\n?", re.MULTILINE)
    if marker_re.search(text):
        text = marker_re.sub(marker, text, count=1)
    else:
        text = text + "\n" + marker
    skill_md_path.write_text(text, encoding="utf-8")
